# Generated by Django 6.0.1 on 2026-02-06 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_date_joined_alter_user_date_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_update',
            new_name='last_updated',
        ),
    ]
