# Generated by Django 6.0.1 on 2026-02-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_date_update_user_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
